language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache: pip
install:
  - pip install coveralls
  - pip install -e .
script:
  - nosetests -v --with-coverage --cover-package=mhkit mhkit
      
after_success:
  - coveralls
