name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pandas>=1.0.0
  - numpy>=1.21.0
  - scipy
  - matplotlib
  - requests
  - lxml
  - scikit-learn
  - statsmodels
  - bottleneck
  - beautifulsoup4
  - xarray
  - h5py>=3.6.0
  - netcdf4>=1.5.8
  - pip:
      - pecos>=0.3.0
      - fatpack
      - NREL-rex>=0.2.63
      - h5pyd>=0.7.0
      - six>=1.13.0
