name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - pip
  - pandas>=1.0.0
  - numpy>=2.0.0
  - pandas>=2.2.2
  - scipy>=1.14.0
  - xarray>=2024.6.0
  - scikit-learn>=1.5.1
  - h5py>=3.11.0
  - h5pyd >=0.18.0
  - statsmodels>=0.14.2
  - requests
  - lxml
  - bottleneck>=1.4.0
  - beautifulsoup4
  - pip:
      - netCDF4>=1.7.1.post1
      - matplotlib>=3.9.1
      - pecos>=0.3.0
      - fatpack
      - NREL-rex>=0.2.63
      - six>=1.13.0
      - notebook
