name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8,<3.12
  - pip
  - pandas>=1.0.0
  - numpy>=2.0.0
  - matplotlib
  - requests
  - lxml
  - scikit-learn
  - statsmodels
  - bottleneck
  - beautifulsoup4
  - xarray
  - h5py>=3.6.0
  - netcdf4>=1.5.8, <=1.6.5
  - pip:
      - scipy>=1.14.0
      - pecos>=0.3.0
      - fatpack
      - NREL-rex>=0.2.63
      - h5pyd>=0.7.0
      - six>=1.13.0
      - notebook
