name: Py 3.7, 3.8, 3.9 | Windows Mac Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"] #, "macos-latest", "windows-latest",]
        python-version: [3.7] #, 3.8, 3.9]

    steps:
    - uses: conda-incubator/setup-miniconda@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        
    - name: Set up Git repository
      uses: actions/checkout@v2
      
    - name: Update and install packages
      run: |
        python -m pip install --upgrade pip wheel
        pip install h5pyd --upgrade
        pip install nose
        pip install coveralls
        pip install .
        
      # python -m pip install --upgrade pip
        # python -m pip install flake8 pytest 
        
    - name: Run nose
      shell: bash -l {0}
      run: |          
        nosetests -v --with-coverage --cover-package=mhkit mhkit
  
    - name: Coveralls
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel: true
        flag-name: Run nose

  coveralls_finish:
    needs: build
    runs-on: ${{ matrix.os }}
    steps:
    - name: Coveralls Finished
      uses: AndreMiras/coveralls-python-action@develop
      with:
        parallel-finished: true

