name: Pylint Loads

on: [push, pull_request]

jobs:
  formatting-and-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install pylint

      - name: Run Pylint on mhkit/loads/
        run: |
          pylint mhkit/loads/extreme/
