name: Test Jupyter Notebooks

on:
  repository_dispatch:
    types: [test-notebooks]

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Generate matrix
        id: set-matrix
        run: |
          python .github/workflows/generate_notebook_matrix.py > matrix.json
          echo "::set-output name=matrix::$(cat matrix.json)"

  test-notebooks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          auto-update-conda: true
          python-version: '3.9'
          activate-environment: TESTconda
          use-only-tar-bz2: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install numpy cython pip hdf5 libnetcdf cftime netcdf4 --strict-channel-priority
          pip install -e . --force-reinstall
          python -m pip install --upgrade pip wheel
          pip install nbval jupyter

      - name: Download non-hindcast data artifact
        uses: actions/download-artifact@v4
        with:
          name: data
          path: ~/.cache/mhkit

      - name: Download wave hindcast data artifact
        if: github.event.client_payload.should_run_hindcast == 'true'
        uses: actions/download-artifact@v4
        with:
          name: wave-hindcast-data
          path: ~/.cache/mhkit/wave-hindcast

      - name: Download wind hindcast data artifact
        if: github.event.client_payload.should_run_hindcast == 'true'
        uses: actions/download-artifact@v4
        with:
          name: wind-hindcast-data
          path: ~/.cache/mhkit/wind-hindcast

      - name: Run non-hindcast notebooks
        run: |
          find examples -name "*.ipynb" -not -name "metocean_example.ipynb" -not -name "WPTO_hindcast_example.ipynb" | while read notebook; do
              jupyter nbconvert --to notebook --execute --inplace --ExecutePreprocessor.timeout=600 "$notebook"
          done

      - name: Run hindcast notebooks
        if: github.event.client_payload.should_run_hindcast == 'true'
        run: |
          for notebook in examples/metocean_example.ipynb examples/WPTO_hindcast_example.ipynb; do
              jupyter nbconvert --to notebook --execute --inplace --ExecutePreprocessor.timeout=600 "$notebook"
          done
