name: Test Jupyter Notebooks

on:
  workflow_run:
    workflows: ['Py 3.8, 3.9, 3.10, 3.11 | Windows Mac Linux']
    types:
      - completed

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Generate matrix
        id: set-matrix
        run: |
          python .github/workflows/generate_notebook_matrix.py > matrix.json
          echo "::set-output name=matrix::$(cat matrix.json)"

  test-notebooks:
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          auto-update-conda: true
          python-version: '3.9'
          activate-environment: TESTconda
          use-only-tar-bz2: true

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install numpy cython pip hdf5 libnetcdf cftime netcdf4 --strict-channel-priority
          pip install -e . --force-reinstall
          python -m pip install --upgrade pip wheel
          pip install nbval jupyter

      - name: Download non-hindcast data artifact
        uses: actions/download-artifact@v4
        with:
          name: data
          path: ~/.cache/mhkit

      - name: Download wave hindcast data artifact
        if: matrix.condition == 'true' && github.event.inputs.should_run_hindcast == 'true'
        uses: actions/download-artifact@v4
        with:
          name: wave-hindcast-data
          path: ~/.cache/mhkit/wave-hindcast

      - name: Download wind hindcast data artifact
        if: matrix.condition == 'true' && github.event.inputs.should_run_hindcast == 'true'
        uses: actions/download-artifact@v4
        with:
          name: wind-hindcast-data
          path: ~/.cache/mhkit/wind-hindcast

      - name: Run notebook
        if: matrix.condition == 'false' || github.event.inputs.should_run_hindcast == 'true'
        run: |
          jupyter nbconvert --to notebook --execute --inplace --ExecutePreprocessor.timeout=600 "${{ matrix.notebook }}"
